## Description
    
A SaaS company seeks to uncover what drives its clients to renew subscriptions. They’ve collected data on client details, subscription records, and economic indicators and would like to connect them to better understand its clients’ behavior. 

They’ve tasked you with analyzing these datasets to identify the key factors influencing clients’ decisions to renew their subscriptions. 

Your analysis will provide them with insights into which customers are renewing their products and the reasons behind their renewals. The company can leverage these insights to make informed decisions to increase renewal rates and improve customer loyalty, helping them stay competitive and ensure long-term growth.


## The Data

The company have provided you with three datasets for your analysis. A summary of each data is provided below.

## `client_details.csv`

| Column         | Description|
|----------------|---------------------------------------------------------------|
| `client_id`    | Unique identifier for each client. |
| `company_size` | Size of the company (Small, Medium, Large).|
| `industry`     | Industry to which the client belongs (Fintech, Gaming, Crypto, AI, E-commerce).|
| `location`     | Location of the client (New York, New Jersey, Pennsylvania, Massachusetts, Connecticut).|

## `subscription_records.csv`

| Column             | Description   |
|--------------------|---------------|
| `client_id`        | Unique identifier for each client.|
| `subscription_type`| Type of subscription (Yearly, Monthly).|
| `start_date`       | Start date of the subscription - YYYY-MM-DD.|
| `end_date`         | End date of the subscription - YYYY-MM-DD.|
| `renewed`          | Indicates whether the subscription was renewed (True, False).|

## `economic_indicators.csv`

| Column           | Description                                       |
|------------------|---------------------------------------------------|
| `start_date`     | Start date of the economic indicator (Quarterly) - YYYY-MM-DD.|
| `end_date`       | End date of the economic indicator (Quarterly) - YYYY-MM-DD.|
| `inflation_rate` | Inflation rate in the period.|
| `gdp_growth_rate`| Gross Domestic Product (GDP) growth rate in the period.|

In [36]:
# Import required libraries
import pandas as pd
import plotly.express as px

# Import data
df_client = pd.read_csv('data/client_details.csv')
df_sub = pd.read_csv('data/subscription_records.csv', parse_dates = ['start_date','end_date'])
df_econind= pd.read_csv('data/economic_indicators.csv', parse_dates = ['start_date','end_date'])

# Sanity Checks

## Client Details

In [2]:
df_client.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   client_id     100 non-null    int64
 1   company_size  100 non-null    object
 2   industry      100 non-null    object
 3   location      100 non-null    object
dtypes: int64(1), object(3)
memory usage: 3.2+ KB

In [3]:
df_client.duplicated().sum()

np.int64(0)

In [4]:
df_client.nunique()

client_id       100
company_size      3
industry          5
location          5
dtype: int64

## Subscription Records

In [5]:
df_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   client_id          100 non-null    int64
 1   subscription_type  100 non-null    object
 2   start_date         100 non-null    datetime64[ns]
 3   end_date           100 non-null    datetime64[ns]
 4   renewed            100 non-null    bool
dtypes: bool(1), datetime64[ns](2), int64(1), object(1)
memory usage: 3.3+ KB

In [6]:
df_sub.duplicated().sum()

np.int64(0)

In [7]:
df_sub.nunique()

client_id            100
subscription_type      2
start_date            97
end_date              97
renewed                2
dtype: int64

## Economic Indicators

In [8]:
df_econind.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       21 non-null     int64
 1   start_date       21 non-null     datetime64[ns]
 2   end_date         21 non-null     datetime64[ns]
 3   inflation_rate   21 non-null     float64
 4   gdp_growth_rate  21 non-null     float64
dtypes: datetime64[ns](2), float64(2), int64(1)
memory usage: 968.0 bytes

In [9]:
df_econind.drop("Unnamed: 0", axis =1, inplace = True)

In [19]:
df_econind.head()

  start_date   end_date  inflation_rate  gdp_growth_rate
0 2018-01-01 2018-03-31            5.77             3.51
1 2018-04-01 2018-06-30            1.17             2.15
2 2018-07-01 2018-09-30            1.56             1.82
3 2018-10-01 2018-12-31            2.78             2.43
4 2019-01-01 2019-03-31            6.91             3.44

# Data Manipulation

In [18]:
# Check keys are the same 
set(df_client["client_id"]) == set(df_sub["client_id"])

True

In [20]:
df_client_sub = df_client.merge(
    df_sub, 
    on = "client_id", 
    how = "left"
)

In [21]:
df_client_sub.head()

,client_id,company_size,industry,location,subscription_type,start_date,end_date,renewed
0,4280387012,Large,Fintech,New York,Yearly,2022-11-25,2023-11-25,True
1,2095513148,Small,Fintech,New Jersey,Monthly,2021-11-03,2021-12-03,False
2,7225516707,Medium,Fintech,Pennsylvania,Yearly,2021-01-19,2022-01-19,True
3,8093537819,Large,Crypto,New York,Monthly,2019-09-14,2019-10-14,False
4,4387541014,Medium,E-commerce,Massachusetts,Monthly,2018-11-08,2018-12-08,False

# Exploratory Data Analysis

In [65]:
fig_comp_size = px.bar(
    df_client_sub,
    x = "company_size",
    color="renewed"
)
fig_comp_size.show()

In [66]:
fig_comp_ind = px.bar(
    df_client_sub,
    x = "industry",
    color = "renewed"
)
fig_comp_ind.show()

In [67]:
fig_loc = px.bar(
    df_client_sub,
    x = "location",
    color = "renewed"
)
fig_loc.show()

In [68]:
fig_sub_type = px.bar(
    df_client_sub,
    x = "subscription_type",
    color="renewed"
)
fig_sub_type.show()

In [64]:
drop_col = ["client_id", "start_date", "end_date"]
group_col = ['company_size', 'industry', 'location', 'subscription_type']
df_client_sub[df_client_sub["renewed"] == True].drop(columns=drop_col).groupby(group_col).size().reset_index(name='renewal_count').sort_values('renewal_count', ascending=False)

   company_size    industry       location subscription_type  renewal_count
46        Small      Gaming     New Jersey            Yearly              2
28       Medium      Gaming   Pennsylvania            Yearly              2
29        Small          AI  Massachusetts           Monthly              2
20       Medium     Fintech     New Jersey           Monthly              2
9         Large     Fintech     New Jersey           Monthly              2
33        Small      Crypto       New York            Yearly              2
25       Medium      Gaming     New Jersey            Yearly              2
0         Large          AI    Connecticut            Yearly              1
35        Small      Crypto   Pennsylvania            Yearly              1
27       Medium      Gaming   Pennsylvania           Monthly              1
30        Small          AI   Pennsylvania           Monthly              1
31        Small      Crypto    Connecticut            Yearly              1
32        Small      Crypto  Massachusetts           Monthly              1
34        Small      Crypto   Pennsylvania           Monthly              1
37        Small  E-commerce  Massachusetts           Monthly              1
36        Small  E-commerce    Connecticut           Monthly              1
38        Small  E-commerce       New York           Monthly              1
39        Small  E-commerce       New York            Yearly              1
40        Small     Fintech    Connecticut           Monthly              1
41        Small     Fintech     New Jersey           Monthly              1
42        Small      Gaming    Connecticut           Monthly              1
43        Small      Gaming  Massachusetts           Monthly              1
44        Small      Gaming  Massachusetts            Yearly              1
45        Small      Gaming     New Jersey           Monthly              1
26       Medium      Gaming       New York            Yearly              1
24       Medium      Gaming     New Jersey           Monthly              1
1         Large          AI       New York            Yearly              1
23       Medium      Gaming  Massachusetts           Monthly              1
2         Large          AI   Pennsylvania           Monthly              1
3         Large      Crypto    Connecticut           Monthly              1
4         Large      Crypto  Massachusetts           Monthly              1
5         Large      Crypto       New York           Monthly              1
6         Large  E-commerce    Connecticut           Monthly              1
7         Large  E-commerce       New York           Monthly              1
8         Large     Fintech    Connecticut           Monthly              1
10        Large     Fintech       New York            Yearly              1
11        Large      Gaming  Massachusetts           Monthly              1
12       Medium          AI   Pennsylvania           Monthly              1
13       Medium      Crypto    Connecticut           Monthly              1
14       Medium      Crypto   Pennsylvania            Yearly              1
15       Medium  E-commerce    Connecticut            Yearly              1
16       Medium  E-commerce  Massachusetts           Monthly              1
17       Medium  E-commerce       New York           Monthly              1
18       Medium     Fintech    Connecticut           Monthly              1
19       Medium     Fintech  Massachusetts            Yearly              1
21       Medium     Fintech   Pennsylvania           Monthly              1
22       Medium     Fintech   Pennsylvania            Yearly              1
47        Small      Gaming   Pennsylvania           Monthly              1

In [47]:
df_client_sub["renewed"].unique()

array([ True, False])

In [49]:
px.bar(
    df_client_sub,
    x = "renewed"
)

In [ ]:
# Next step: Include df_ecoomic_indicator in the analysis